### ISSUE TITLE
启动太麻烦了，启动软件的打开三个cmd窗口，两个yarn start都是进入的死循环

### ISSUE THREAD

**Issue by VenomBat** [Y-qwq/Y-Music#3]

**Comment by Y-qwq** [comment]
= =这个我也没办法，一个是启动接口服务的，一个react的程序，最后一个是启动electron程序。
不过接口那个不用启动都行，我src/util/api.js里面忘了把HOSTNAME改回localhost:5000，现在直接就是服务器上的地址。

**Comment by Y-qwq** [comment]
@VenomBat 两个yarn start的位置是不同，不冲突。
